### ISSUE TITLE
Access to Flower Panel 

### ISSUE THREAD

**Issue by mabdullah22** [SigmaGmbH/Bug-Bounty-1.0#10]
### 1. **Bug/Vulnerability Description**

Access to Flower Panel at https://bench.panel.swisstronik.com/flower/

### 2. **Hardware and Software Specifications**

N/A

### 3. **Steps to Reproduce**

An instance of Flower is deployed at https://bench.panel.swisstronik.com/flower/ to monitor the celery and rabbitmq ,

There is no authentication applied hence anyone can visit and analyze the dashboard.
https://bench.panel.swisstronik.com/flower/worker/celery%40645c1a77c0b0#tab-config

Partial Configs can also been seen https://bench.panel.swisstronik.com/flower/worker/celery%40000be2b178b1#tab-config 

### 4. **Impact Analysis**

An attacker can gain insights on backend deployments.

### 5. **Code Fix Submission**

Proper authentication should be applied on the instance.

### 6. **Choose the Right Label**

Security Issue

### 7. **Additional Context** 

<img width="1512" alt="Screenshot 2023-10-13 at 9 18 36 PM" src="https://github.com/SigmaGmbH/Bug-Bounty-1.0/assets/31371789/22d750cf-a0fc-4955-90f1-9e4630a30588">

---

Thank you for contributing to the improvement of our project!👨‍💻👩‍💻

---

## Swisstronik internal use only

- [ ] Not duplicate issue
- [ ] Appropriate labels applied

**Comment by iNadirAli** [comment]
@santiagotrujilloz Please Check

**Comment by SantiagoDevRel** [comment]
Hi @mabdullah22 , issues related to the servers are out of the scope of the Bug Bounty. Anyway, we really appreciate your efforts, and that's why we will reward you with 200usdt + 333swtr tokens for the issues you published regarding the server: [Issue #10](https://github.com/SigmaGmbH/Bug-Bounty-1.0/issues/10/), [Issue #9](https://github.com/SigmaGmbH/Bug-Bounty-1.0/issues/9), [Issue #8](https://github.com/SigmaGmbH/Bug-Bounty-1.0/issues/8)

[Hall of fame](https://github.com/SigmaGmbH/Bug-Bounty-1.0/blob/main/Hall%20Of%20Fame/bug_report_by_mabdullah22_server.md)
