### ISSUE TITLE
Leakage of Encrypted Keys in Wallet

### ISSUE THREAD

**Issue by mabdullah22** [SigmaGmbH/Bug-Bounty-1.0#12]
### 1. **Bug/Vulnerability Description** 
Leakage of Encrypted Keys In chrome wallet

### 2. **Hardware and Software Specifications** 
- Chrome

### 3. **Steps to Reproduce** 
1. Forget your password
2. Inspect the console.

### 4. **Impact Analysis** 
Attacker having access to users browser can initiate this attack and steal the encrypted keys. Bruteforce attack can be initiated since we have salt too. 

### 5. **Code Fix Submission** 
Disable the logging of critical info in console.

### 6. **Choose the Right Label** 
Security Issue: Critical

### 7. **Additional Context** 
I have attached a POC video showing the issue.
https://drive.google.com/file/d/1L2Z1uIOi57YK1R2VADQbl3W4yXKgruP6/view?usp=sharing

____

Thank you for contributing to the improvement of our project!👨‍💻👩‍💻
____

## Swisstronik internal use only
- [ ] Not duplicate issue
- [ ] Appropriate labels applied

**Comment by SantiagoDevRel** [comment]
Hi @mabdullah22 , issues related to the wallet are out of the scope of the Bug Bounty. Anyway, we really appreciate your efforts, and that's why we will reward you with 150usdt + 250swtr tokens for the issues you published regarding the wallet: [Issue#13](https://github.com/SigmaGmbH/Bug-Bounty-1.0/issues/13), Issue#12(this one) and [Issue#11](https://github.com/SigmaGmbH/Bug-Bounty-1.0/issues/11) 

[Hall of fame](https://github.com/SigmaGmbH/Bug-Bounty-1.0/blob/main/Hall%20Of%20Fame/bug_report_by_mabdullah22_wallet.md)
